### ISSUE TITLE
Incompatible with PyCharm 242.*  

### ISSUE THREAD

**Issue by ewi2345** [dubreuia/python-inlay-hints-plugin#10]
Pls see attached image 
![Screenshot 2024-06-11 051138](https://github.com/dubreuia/python-inlay-hints-plugin/assets/15355566/8cf0faa4-9ffa-438d-8e49-c18978f5b6ab)

**Comment by dubreuia** [comment]
https://github.com/dubreuia/python-inlay-hints-plugin/releases/tag/v1.8.0

Published on jetbrains marketplace, should be available in your IDE soon
