### ISSUE TITLE
Not compatible with PyCharm 2022.1

### ISSUE THREAD

**Issue by autoferrit** [dubreuia/python-inlay-hints-plugin#2]
Plugin is no longer compatible or usable for the new version of PyCharm 2022.1
![image](https://user-images.githubusercontent.com/89895/163841476-7febc53f-1f86-4420-b94e-d65c0254a1b0.png)

**Comment by dubreuia** [comment]
Thanks @autoferrit , I'll look into it

**Comment by autoferrit** [comment]
I am having the issue in https://github.com/dubreuia/python-inlay-hints-plugin/issues/3 as well. Any updates on getting these fixed?

**Comment by dubreuia** [comment]
It is a newer version than the original issue

I've looked into it last week, but I'm having trouble building the plugin with new versions. I'll try to fix this week

**Comment by agatti** [comment]
All it takes to at least run the plugin in the sandbox is as such:

```diff
diff --git a/build.gradle.kts b/build.gradle.kts
index e487e2a..cbcc714 100644
--- a/build.gradle.kts
+++ b/build.gradle.kts
@@ -10,7 +10,7 @@ plugins {
     // Kotlin support
     id("org.jetbrains.kotlin.jvm") version "1.6.0"
     // Gradle IntelliJ Plugin
-    id("org.jetbrains.intellij") version "1.3.0"
+    id("org.jetbrains.intellij") version "1.6.0"
     // Gradle Changelog Plugin
     id("org.jetbrains.changelog") version "1.3.1"
     // Gradle Qodana Plugin
diff --git a/gradle.properties b/gradle.properties
index 7e9f557..08410f1 100644
--- a/gradle.properties
+++ b/gradle.properties
@@ -9,11 +9,11 @@ pluginVersion = 1.0.1
 # See https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html
 # for insight into build numbers and IntelliJ Platform versions.
 pluginSinceBuild = 203
-pluginUntilBuild = 221.*
+pluginUntilBuild = 222.*

-# IntelliJ Platform Properties -> https://github.com/JetBrains/gradle-intellij-plugin#intellij-platform-properties
+# IntelliJ Platform Properties -> https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#intellij-extension
 platformType = PC
-platformVersion = 2020.3.4
+platformVersion = 2022.2.1
 downloadSources = false

 # Plugin Dependencies -> https://plugins.jetbrains.com/docs/intellij/plugin-dependencies.html
```

I haven't tested with anything older than 2022.2.1, but I guess you've got the CI infrastructure set up to do that yourself :)

**Comment by dubreuia** [comment]
> All it takes to at least run the plugin in the sandbox is as such:

thanks for code @agatti!

> but I guess you've got the CI infrastructure set up to do that yourself :)

lol you greatly overestimate my super scrappy setup

**Comment by dubreuia** [comment]
Sorry I'm so slow thanks for the wait fixed in https://github.com/dubreuia/python-inlay-hints-plugin/releases/tag/v1.1.0 will release on jetbrains marketplace
