### ISSUE TITLE
Not compatible with PyCharm 2022.2

### ISSUE THREAD

**Issue by Jonadabe** [dubreuia/python-inlay-hints-plugin#3]
![PyCharm-incompatible-2022-08-05_121738](https://user-images.githubusercontent.com/986504/183066981-9e01998d-4ef7-4637-bfc0-f8a671fa8ddd.jpg)

# PyCharm 2022.2 (Community Edition)
Build #PC-222.3345.131, built on July 27, 2022
Runtime version: 17.0.3+7-b469.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 998M
Cores: 4
Registry:
    documentation.show.toolbar=true

Non-Bundled Plugins:
    ski.chrzanow.foldableprojectview (1.1.3)
    net.seesharpsoft.intellij.plugins.csv (2.19.0)
    name.kropp.intellij.makefile (222.3345.108)
    lermitage.intellij.extratci (1.23.0.201)
    com.jetbrains.plugins.ini4idea (222.3345.144)
    com.intellij.tide (222.3345.108)
    bundled-pycharm-help (222.3345.131)
    mobi.hsz.idea.gitignore (4.4.2)
    com.github.shiraji.emoji (3.1.0)
    ru.meanmail.plugin.requirements (2022.3-222-EAP-SNAPSHOT)
    org.tonybaloney.security.pycharm-security (1.26.0)
    org.reloadium (0.8.3)
    nl.jusx.pycharm.lineprofiler (1.7.0)
    me.aristotll.python.typing.adder (1.1)
    io.github.donkirkby.livepycharm (4.8.0)
    com.leinardi.pycharm.pylint (0.14.0)
    com.koxudaxi.pydantic (0.3.13)
    com.github.ArtsiomCh.NestedBracketsColorer (0.6.0)
    cms.rendner.intellij.py-styled-dataframe-viewer (0.8.0)
    cms.rendner.intellij.py-prefix-fstring-plugin (1.1)
    com.github.shiraji.yaemoji (1.0.7)
    Batch Scripts Support (1.0.13)

**Comment by dubreuia** [comment]
Sorry I'm so slow thanks for the wait fixed in https://github.com/dubreuia/python-inlay-hints-plugin/releases/tag/v1.1.0 will release on jetbrains marketplace
