### ISSUE TITLE
JetBrain 2024.1 issues

### ISSUE THREAD

**Issue by ewi2345** [dubreuia/python-inlay-hints-plugin#8]
I would hate to lose access to ur tool when upgrading to 2024.1 
Don't know if u already know about it
Erland
![Screenshot 2024-02-01 054037](https://github.com/dubreuia/python-inlay-hints-plugin/assets/15355566/ec5acad6-32cc-4342-9a71-99e056160725)

**Comment by dubreuia** [comment]
Thanks @ewi2345 fixed in https://github.com/dubreuia/python-inlay-hints-plugin/releases/tag/v1.6.0 it will be released to the jetbrains marketplace tomorrow or the day after

**Comment by ewi2345** [comment]
Unfortunately, 1.6 is not accepted in 2024.1 EAP even in the latest EAP 4 - 
![Screenshot 2024-02-09 071659](https://github.com/dubreuia/python-inlay-hints-plugin/assets/15355566/bfb28819-8cc9-4815-85b5-43360b2135a3)
![Screenshot 2024-02-09 072515](https://github.com/dubreuia/python-inlay-hints-plugin/assets/15355566/a2908a95-d8e8-4ea6-b37a-f7e106713729)

**Comment by ewi2345** [comment]
I confirm:1.7 works
